### ISSUE TITLE
Display failed codemagic builds in PRs

### ISSUE THREAD

**Issue by lukesleeman** [Western-Health-Covid19-Collaboration/wh_covid19_app#98]
I investigated some PRs that got stuck last night:

https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/pull/89
https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/pull/82

And it seems the build is actually failing due to code style errors.  However if you look at the PR it looks like we are just waiting on the build to complete:?

![image](https://user-images.githubusercontent.com/902252/77695617-26b61700-7000-11ea-9943-e0a431fd1d5d.png)

Yet if you go into codemagic, its failed:  https://codemagic.io/app/5e75f4bfdd1d6d000a198e90/build/5e7c92e629657a000e2e3ebc

It would be good to show the failed build status in the PR

**Comment by lukesleeman** [comment]
Just checking in with @maks and @workerbee22  on this one - is it something simple we can easily fix up, a bug with codemagic, or some huge bit of work?

**Comment by workerbee22** [comment]
@maks is looking at it

**Comment by maks** [comment]
@lukesleeman yes, I fixed it a few days ago, I think the overnight missing statuses is because Codemagic support has reported they had some issues with recent maintenance and had to do a DB rollback.

**Comment by lukesleeman** [comment]
Cool.  You happy for me to close this issue then?

**Comment by lukesleeman** [comment]
Just an update, I saw this happening again last night, so it seems whatever is happening at the CM end with their DB's hasn't been fixed yet

**Comment by lukesleeman** [comment]
It's still occurring on and off, but I don't think there is much we can actually do about it.  We have a reasonable work around which is to just push through a small commit to kick off the build again.

Perhaps I could update the `Readme.md` with the work around and then we can close this issue.  What do you think @maks ?

**Comment by maks** [comment]
@lukesleeman :+1: This seems to actually be mostly a Github issue. Looking on CI, they complete successfully and since *i* wrote the work-around script that notifies Github I think its actually error on their end but with GH so swamped and unresponsive at the moment not much more we can do. I'll add a note to the Readme for this.

**Comment by lukesleeman** [comment]
> @lukesleeman 👍 This seems to actually be mostly a Github issue. Looking on CI, they complete successfully and since _i_ wrote the work-around script that notifies Github I think its actually error on their end but with GH so swamped and unresponsive at the moment not much more we can do. I'll add a note to the Readme for this.

No worries, close this issue once we have the note in the readme.  Might also be good to add something to the FAQ section of the github101.md as well 🙂

**Comment by lukesleeman** [comment]
Assigning to me to update the readme.
